language: node_js
node_js:
  - "node"
cache: yarn
branches:
  only:
    - master
addons:
  ssh_known_hosts: 138.68.85.252
before_install:
- openssl aes-256-cbc -K $encrypted_113a7075fbd8_key -iv $encrypted_113a7075fbd8_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
script:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends zip

  - yarn
  - yarn jest

  - zip -q -r reart-archive.zip .
  - ls -l reart-archive.zip
  - scp -v -C reart-archive.zip slyshadow@138.68.85.252:~/node/.
  - ssh slyshadow@138.68.85.252 '
      cd ~/node/ &&
      mkdir -p reart &&
      unzip -qo reart-archive.zip -d reart-new &&
      rm -f reart-archive.zip &&
      mv reart reart-old &&
      mv reart-new reart &&
      cp reart-config/app.json reart &&
      cd reart &&
      pm2 delete -s reart || true &&
      pm2 start app.json &&
      rm -rf ../reart-old &&
      exit'
