type Product {
    id: Int!
    owner_id: Int!
    name: String!
    description: String!
    code: String!
    price: Int!
    author: String!
    url: String!
}

input getProductInput {
    id: Int!
}

extend type Query {
    getProducts: [Product!]! # get all products
    getProduct(input: getProductInput!): [Product!]! # get single product
}